[script]
name = "wr_official"
version = "0.1.0"
author_ids = ["MotorcycleEnjoyer"]
description = "Help people get started easier"
repository = "https://github.com/MotorcycleEnjoyer/Sample_WR_Mod.git"
tags = ["official", "wr"]

[dependencies]
partitions = "0.1.0"
