[script]
name = "wr_official"
version = "0.1.0"
author_ids = ["YourName"]
description = "YourDescription"
repository = "https://youNeedAtLeastOneLetterHere"
tags = ["official", "wr"]

[dependencies]
partitions = "0.1.0"
